In [1]:
import numpy as np
a1=np.array([10,20,40,60,30,50])
print(a1) #standared representation of numpy array[]around the element when u print array object directly.

[10 20 40 60 30 50]


In [2]:
print(*a1)# * before al unpack the array elements,tretating them as a seprate arguments.by deafult
#the print function seprates multiple arguments with a space.

10 20 40 60 30 50


In [3]:
a1=np.array((10,20,40,60,30,50))
print(a1)
print(*a1)

[10 20 40 60 30 50]
10 20 40 60 30 50


**Creation of numPy Array**

In [4]:
a1=np.array([1,2,3,4]) #1D Array
a1.dtype
print(*a1)
print(a1)

1 2 3 4
[1 2 3 4]


In [5]:
a2=np.array([[1,2,3],[4,5,6]]) #2D Array
a2.dtype
print(a2)

[[1 2 3]
 [4 5 6]]


In [6]:
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #3D array
a3.dtype
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
a4=np.array([1,2,3,4],ndmin=5)
print(a4)


[[[[[1 2 3 4]]]]]


In [8]:
a5=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [11,12,14]
],ndmin=5)
print(a5)


[[[[[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]
    [11 12 14]]]]]


In [9]:
a6=np.array([[1,2],[3,4],['5','6']]) #one is in str form all will convert into str.
print(a6)

[['1' '2']
 ['3' '4']
 ['5' '6']]


In [10]:
a6=np.array([[1,2],[3,4.5],['5','6']])
print(a6)

[['1' '2']
 ['3' '4.5']
 ['5' '6']]


In [11]:
a6=np.array([[1,2],[3,4.5],[5,6]]) #All will convert into decimal.
print(a6)

[[1.  2. ]
 [3.  4.5]
 [5.  6. ]]


In [12]:
a6=np.array([[1,2],[3j,4],[5.5,6]]) # change according to superior Hierarchy.
print(a6)

[[1. +0.j 2. +0.j]
 [0. +3.j 4. +0.j]
 [5.5+0.j 6. +0.j]]


**Boolean----Integer----Float----Complex----string/object Superoir from last to First**

**Creating Array with Data Type**

In [13]:
a7=np.array([1,2,3,4],dtype='i4')
print(a7)

[1 2 3 4]


In [14]:
a8=np.array([1,2,3,4],dtype='int32')
print(a8)

[1 2 3 4]


In [15]:
a9=np.array([1,2,3,4],dtype = 'f4')
print(a9)

[1. 2. 3. 4.]


In [16]:
a9=np.array([1,2,3,4],dtype='S')
print(a9)

[b'1' b'2' b'3' b'4']
