**Size in NumPy Array**

In [14]:
import numpy as np
a1=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
type(a1)
a1.dtype
a1.size #(Size means total no of element(value) inside array.
a2=np.array([[[],[],[]],[[],[],[]]])
type(a1)
a2.size
a2.ndim
a1.ndim
a3=np.array(35) #0 Dimension
a3.size
a3.ndim


0

**T0 know Dimension of Array**

In [12]:
print(a1)
a1.ndim
a2.ndim

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


3

**To Specify Dimension**

In [18]:
a4=np.array([1,2,3],ndmin=5)
a4.ndim

5

**Shape In NumPy Array**

In [21]:
a4=np.array([[1,2,3]])
a4.shape
print(a1)
a1.shape

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(4, 3)