**Zeros Function**

In [1]:
import numpy as np
a1=np.zeros((3,1,)) # 3Arrays
                   # 1-1 digit inside array.
print(a1)
a1.ndim
a1.dtype

[[0.]
 [0.]
 [0.]]


dtype('float64')

**Ones Function**

In [2]:
a1=np.ones((3,1),dtype='i4') # u can put int or any data type by dtype='i4'.
print(a1)


[[1]
 [1]
 [1]]


**Full Functions**

In [3]:
a1=np.full((3,3),2,dtype='i4')
print(a1)
a1=np.full((444,444,),444,dtype='i4')
print(a1)
type(a1)
a1.ndim

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[444 444 444 ... 444 444 444]
 [444 444 444 ... 444 444 444]
 [444 444 444 ... 444 444 444]
 ...
 [444 444 444 ... 444 444 444]
 [444 444 444 ... 444 444 444]
 [444 444 444 ... 444 444 444]]


2

**ARANGE Function**

In [4]:
a1=np.arange(5)
a1

array([0, 1, 2, 3, 4])

In [5]:
a1=np.arange(5,10)
print(a1)
a1=np.arange(12)
a1


[5 6 7 8 9]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
a1=a1.reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a1=np.linspace(1,10,3) #first value ,last value and find how many value u want find.
print(a1)
a1=np.linspace(2,40,8)
print(a1)
a1=np.linspace(1,80,5)
a1

[ 1.   5.5 10. ]
[ 2.          7.42857143 12.85714286 18.28571429 23.71428571 29.14285714
 34.57142857 40.        ]


array([ 1.  , 20.75, 40.5 , 60.25, 80.  ])

In [8]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='f4') #It keeeps always float when use (nan)function.
print(a1)
a1[2,1]=np.nan
print(a1)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7. nan  9.]]


In [9]:
a1=np.identity(10,dtype='i4')
print(a1)

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]


In [10]:
a1=np.identity(4,dtype='i4')
print(a1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [11]:
a1=np.random.rand(3,4)#taking random number. random generally generate 0 to 1.
a1
a1=np.random.randint(10,15,size=(3,4))# Taking range it takes range 10 to 15 and 15 will exclude.
print(a1)
                     

[[12 14 11 11]
 [13 11 12 10]
 [13 14 14 12]]
